import type { Profile, Request } from '../types'

export const DEV_BYPASS = import.meta.env.VITE_DEV_BYPASS_AUTH === 'true'

export const MOCK_PROFILE: Profile = {
  id: 'dev-user-001',
  name: 'Camille Dev',
  email: 'camille@ynov.com',
  filiere: 'Dev Web',
  skills: ['React', 'TypeScript', 'Figma'],
  available: true,
  campus_radius: 'campus',
  push_subscription: null,
  created_at: new Date().toISOString(),
}

const now = Date.now()

export const MOCK_REQUESTS: Request[] = [
  {
    id: 'req-001',
    author_id: 'dev-user-002',
    title: 'Câble HDMI pour soutenance dans 10 min',
    description: 'J\'ai besoin d\'un câble HDMI pour brancher mon Mac à la TV de la salle B204.',
    category: 'cable',
    target_filieres: ['Dev Web', 'Design UX'],
    location: 'Bât. B · Salle 204',
    urgent: true,
    duration_min: 15,
    expires_at: new Date(now + 12 * 60 * 1000).toISOString(),
    status: 'active',
    created_at: new Date(now - 3 * 60 * 1000).toISOString(),
    author: {
      id: 'dev-user-002',
      name: 'Lucas Martin',
      email: 'lucas@ynov.com',
      filiere: 'Dev Web',
      skills: [],
      available: true,
      campus_radius: 'campus',
      push_subscription: null,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'req-002',
    author_id: 'dev-user-003',
    title: 'Avis rapide sur mon flow Figma avant rendu',
    description: 'J\'ai un doute sur ma hiérarchie visuelle, besoin d\'un regard extérieur.',
    category: 'design',
    target_filieres: ['Design UX'],
    location: 'Cafétéria RDC',
    urgent: false,
    duration_min: null,
    expires_at: null,
    status: 'active',
    created_at: new Date(now - 8 * 60 * 1000).toISOString(),
    author: {
      id: 'dev-user-003',
      name: 'Inès Dubois',
      email: 'ines@ynov.com',
      filiere: 'Design UX',
      skills: ['Figma', 'UX Research'],
      available: true,
      campus_radius: 'campus',
      push_subscription: null,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'req-003',
    author_id: 'dev-user-004',
    title: 'Bug React bizarre sur un useEffect, qui peut aider ?',
    description: null,
    category: 'code',
    target_filieres: ['Dev Web', 'Dev Logiciel'],
    location: 'Open space · 3ème étage',
    urgent: true,
    duration_min: 30,
    expires_at: new Date(now + 25 * 60 * 1000).toISOString(),
    status: 'active',
    created_at: new Date(now - 1 * 60 * 1000).toISOString(),
    author: {
      id: 'dev-user-004',
      name: 'Tom Lefevre',
      email: 'tom@ynov.com',
      filiere: 'Dev Logiciel',
      skills: ['Python', 'C++'],
      available: false,
      campus_radius: 'building',
      push_subscription: null,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'req-004',
    author_id: 'dev-user-005',
    title: 'Quelqu\'un a ses notes du cours d\'archi logicielle ?',
    description: 'J\'étais absent la semaine dernière, besoin du cours sur les design patterns.',
    category: 'cours',
    target_filieres: ['Dev Logiciel'],
    location: 'Bibliothèque',
    urgent: false,
    duration_min: null,
    expires_at: null,
    status: 'active',
    created_at: new Date(now - 22 * 60 * 1000).toISOString(),
    author: {
      id: 'dev-user-005',
      name: 'Sara Aziz',
      email: 'sara@ynov.com',
      filiere: 'Dev Logiciel',
      skills: [],
      available: true,
      campus_radius: 'promo',
      push_subscription: null,
      created_at: new Date().toISOString(),
    },
  },
]
